name: crypto.ts
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: denoland/deno:1.11.2

        steps:
        - uses: actions/checkout@v2
        - run: apt-get update && apt-get install make
        - run: make all
